### PR TITLE
Update faraday to 0.9

### PR DESCRIPTION
**Pull request by tekwiz**

### CODE REVIEW

**Comment by ryanlecompte** [comment]
Fantastic! Thanks for keeping this library alive. :-)

**Comment by ryanlecompte** [comment]
@tekwiz, I've made you a contributor so that you have full commit access. Thanks for helping maintain this library and feel free to push out a new version of the gem with these changes. Thanks!

**Comment by madrobby** [comment]
It's great to see these updates! We're working on a V2 of the Freckle API. Once we have a beta of this up and running, I will make sure that you guys get access to it.

**Comment by tekwiz** [comment]
@ryanlecompte Thank-you greatly!  We found a couple other issues yesterday afternoon that I'm about to push fixes for.  Since we're in active development on a project using this gem, we'll give it a whirl today and if things look good I'll bump to v0.3.0.

**Comment by tekwiz** [comment]
@madrobby We'd love that! Thanks!

**Pull request merged**
